# Generated by Django 4.1 on 2022-08-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='choice',
            field=models.CharField(choices=[('left', 'left'), ('right', 'right')], default='left', max_length=5),
            preserve_default=False,
        ),
    ]
