# Generated by Django 4.1 on 2022-08-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_game_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
