# Generated by Django 4.1 on 2022-08-26 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoWallet',
            fields=[
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.IntegerField(default=10000)),
            ],
        ),
    ]
