# Generated by Django 4.1 on 2022-08-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_demowallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='demo_game',
            field=models.BooleanField(default=False),
        ),
    ]
