# Generated by Django 3.2.3 on 2022-08-30 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_game_demo_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_game_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='new_game_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BonusGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('winning', models.BooleanField(default=False)),
                ('winning_amount', models.IntegerField()),
                ('choice', models.CharField(choices=[('left', 'left'), ('middle', 'middle'), ('right', 'right')], max_length=6)),
                ('demo_game', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
