# Generated by Django 3.2.3 on 2022-09-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20220830_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusgame',
            name='winning_amount',
            field=models.IntegerField(null=True),
        ),
    ]
