# Generated by Django 3.2.3 on 2022-10-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20221003_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keysbonus',
            new_name='Keys',
        ),
    ]
