# Generated by Django 3.2.3 on 2022-10-03 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_rename_keysbonus_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keys',
            name='id',
        ),
        migrations.RemoveField(
            model_name='keys',
            name='user',
        ),
        migrations.AddField(
            model_name='keys',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
