# Generated by Django 3.2.3 on 2022-10-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20221003_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keys',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Keys',
        ),
    ]
